<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


    <xs:element name="catalogo">
        <xs:complexType>
            <xs:sequence>


                <xs:element name="libros">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="libro" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titulo" type="xs:string"/>
                                        <xs:element name="anio" type="xs:integer"/>

                                        <xs:element name="autores">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="autor" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="nombre" type="xs:string"/>
                                                                <xs:element name="orcid" type="xs:string" minOccurs="0"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                

                                        <xs:element name="etiquetas" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="etiqueta" type="xs:string" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                        
                                    </xs:sequence>

                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                    <xs:attribute name="categoria" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="novela"/>
                                                <xs:enumeration value="tecnico"/>
                                                <xs:enumeration value="ciencia"/>
                                                <xs:enumeration value="arte"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="isbn" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                


                <xs:element name="revistas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="revista" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titulo" type="xs:string"/>
                                        <xs:element name="anio" type="xs:integer"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                    <xs:attribute name="area" type="xs:string" use="required"/>
                                    <xs:attribute name="issn" type="xs:string" use="required"/>
                                    <xs:attribute name="numero" type="xs:integer" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>


                <xs:element name="usuarios">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="usuario" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="email">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value=".+@.+\..+"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>

                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                    <xs:attribute name="tipo" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="alumno"/>
                                                <xs:enumeration value="profesor"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>


                <xs:element name="prestamos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="prestamo" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="fecha_inicio" type="xs:date"/>
                                        <xs:element name="fecha_fin" type="xs:date" minOccurs="0"/>

                                        <xs:element name="estado">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="activo"/>
                                                    <xs:enumeration value="devuelto"/>
                                                    <xs:enumeration value="retrasado"/>
                                                    <xs:enumeration value="en_curso"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                    <xs:attribute name="itemRef" type="xs:IDREF" use="required"/>
                                    <xs:attribute name="usuarioRef" type="xs:IDREF" use="required"/>

                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>

            <xs:attribute name="fecha" type="xs:date" use="required"/>

        </xs:complexType>
    </xs:element>

</xs:schema>
